version: '3.4'

services:
  puzolabs.hamikdash.server:
    image: ${DOCKER_REGISTRY-}puzolabshamikdashserver
    build:
      context: .
      dockerfile: PuzoLabs.Hamikdash.Server/Dockerfile

  puzolabs.hamikdash.reservations:
    image: ${DOCKER_REGISTRY-}puzolabshamikdashreservations
    build:
      context: .
      dockerfile: PuzoLabs.Hamikdash.Reservations/Dockerfile

  postgres:
    image: postgres:13.3
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./postgres/initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "15432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER-admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD-admin}
    command: "postgres -c 'shared_buffers=2500MB' -c 'max_connections=1000'"
    labels:
      - "co.elastic.logs/enabled=true"
      - "co.elastic.logs/fileset.stdout=access"
      - "co.elastic.logs/fileset.stderr=error"
      - "co.elastic.logs/processors.add_fields.fields.colony.application=postgres"
      - "co.elastic.logs/processors.add_fields.target="
      - "co.elastic.logs/module=postgresql"
volumes:
  postgres-data:
